name = "RandomAhhPack"
author = "Malasaur"
version = "0.1.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b17715370ad89b268695adb7160635cad28e272d89dcdd3d8bc45003308d4b19"

[versions]
fabric = "0.16.13"
minecraft = "1.20.1"
