minY = -85
maxY = 60
disableVanillaMineshafts = true

[spawnRates]
lanternSpawnRate = 0.0067
torchSpawnRate = 0.02
workstationSpawnRate = 0.025
workstationDungeonSpawnRate = 0.25
smallShaftSpawnRate = 0.07
cobwebSpawnRate = 0.15
smallShaftChestMinecartSpawnRate = 0.003
mainShaftChestMinecartSpawnRate = 0.03
smallShaftTntMinecartSpawnRate = 0.0024999999441206455
mainShaftTntMinecartSpawnRate = 0.0024999999441206455
zombieVillagerRoomSpawnChance = 2
smallShaftPieceChainLength = 18

[ores]
enabled = true
cobble = 75
coal = 30
iron = 15
redstone = 20
gold = 13
lapis = 5
emerald = 5
diamond = 5
